### ISSUE TITLE
Waybar unable to subscribe to ipc event

### ISSUE THREAD

**Issue by Anomalocaridid** [AR-CADE/wayfire-ipc#1]
Waybar's `sway/workspaces` module does not work with wayfire-ipc. When I try to run waybar with the `sway/workspaces` module, I get the error in its output:

```
[2023-01-24 18:16:38.521] [warning] module sway/workspaces: Disabling module "sway/workspaces", Unable to subscribe ipc event
```

This also applies to the `sway/modes` module, although I do not know if waybar has 'modes' like how sway does anyways.

P.S. Thanks a lot for making this plugin!

**Comment by AR-CADE** [comment]
Thanks for your report,

this should be fixed on both master and 0.7.x branches.

**Comment by Anomalocaridid** [comment]
It looks like it is fixed. Thank you!

Also it looks like `ipc-server` needs to be listed before `autostart` in the list of enabled plugins when using `autostart` to launch waybar in order for them to successfully connect. It's not a problem, but I figured it would be helpful for you to know.

**Comment by AR-CADE** [comment]
> Also it looks like `ipc-server` needs to be listed before `autostart` in the list of enabled plugins when using `autostart` to launch waybar in order for them to successfully connect. It's not a problem, but I figured it would be helpful for you to know.

Yes of course, the order in the plugin list is important, thank for pointing this .
